### ISSUE TITLE
How to save file with original name, not a random tmp_name?

### ISSUE THREAD

**Issue by hcaihao** [antonheryanto/lua-resty-post#2]
I think it cannot be supported, Do you consider adding this feature?

**Comment by antonheryanto** [comment]
@hcaihao  sorry the docs are not clear. to save file with original name is supported. when uploading files lua-resty-post will produce tables which has files tables index by input file name (follow php upload object name). example:

``` html
<input type="file" name="upload" value="test.pdf">
```

table produce by lua-resty-post

``` lua
{
  files = {
    upload = {
      name = "test.pdf", -- original file name
      type = "application/pdf", -- mime type
      size = 27672, -- 27KB
      tmp_name = "1460691521.0872"
    }
  }
}
```

so to save the file to original name just rename tmp_name to name

``` lua
local resty_post = require "resty.post"
local post = resty_post:new()
local m = post:read()
local file = m.files.upload
os.rename(post.path.. file.tmp_name, target_path .. file.name)
```

**Comment by hcaihao** [comment]
Yes, I know this method, I means if the post can write file with original name immediately, no need rename by myself.

**Comment by hcaihao** [comment]
I think it's better to add an option to lua-resty-post

**Comment by antonheryanto** [comment]
thank for suggestion, push new version which still API compatible but add feature by specify
the options. Instead only specify path now add more options

``` lua
local resty_post = require "resty.post"
local post = resty_post:new({
  path = /tmp, -- 
  no_tmp = true, -- return orginal file name
  name = function(name, field) return field.."_"..name end, -- name function pattern,
  chunk_size = 10240 -- resty.upload chunk size
})
```

or

``` lua
local resty_post = require "resty.post"
local post = resty_post:new()
function post.name(name, field)
  return field.."_"..name end
end
```

**Comment by hcaihao** [comment]
got it, good idea
