### ISSUE TITLE
HTTP method Option support

### ISSUE THREAD

**Issue by linuxsupport2** [antonheryanto/lua-resty-post#4]
Hi, many of upload plugins ie jquery-upload use OPTION instead of POST
it does not seem to work with lua-resty-post

**Comment by antonheryanto** [comment]
have look to the jquery upload plugin example, its uses OPTIONS for detection and cross site handling (CORS). your need to implement upload server handler which provides response to HTTP OPTIONS request method and uses lua-resty-post to handle the HTTP POST for upload. so handling options is outside scope of lua-resty-post. correct me if I am wrong and provides me with simple sample which could reproduce your problem.

example location part of nginx.conf: (not tested)

``` lua
location /upload {
  content_by_lua_block {
     local post = require "resty.post":new()
     local method = ngx.var.request_method

     if method == "OPTIONS" then
       local header = ngx.header
       header['Access-Control-Allow-Origin'] = '*'
       header['Access-Control-Allow-Methods'] = 'GET,POST,PUT,DELETE,HEAD,OPTIONS'
     elseif method == "POST" then
       local m = post:read()
       -- process your files
     end
  }
}
```

**Comment by antonheryanto** [comment]
will close this, please reopen if consider not resolve
