### ISSUE TITLE
upload an image

### ISSUE THREAD

**Issue by rahulpatel033** [antonheryanto/lua-resty-post#5]
help wanted.
` local m = post:read()` 
I checked the data it's fine but now how do I upload a file? could you post some code to upload image using lua?

**Comment by antonheryanto** [comment]
there is simple sample in readme.

but for clarity when u have upload image html page

```html
<form action="/uploadimage" method="post" enctype="multipart/form-data">
  <input type="file" name="upload" accept="image/*">
  <button>Upload</button>
</form>
```

define action on server
```nginx.conf
location /save {
  content_by_lua_file image.lua;
}
```
image.lua
```lua
local resty_post = require "resty.post"
local post = resty_post:new({
  path = "/my/path",           -- path upload file will be saved
  name = function(name, field) -- overide name with user defined function
    return name.."_"..field 
  end
})
local m = post:read()
```
you could define path to upload and template name
or you process the the result post object (files) and adjust according to your need


will improve readme for better usage example later

**Comment by rahulpatel033** [comment]
Thanks a lot @antonheryanto . It's working.
